expense-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office 1</fullName>
                </value>
                <value>
                    <fullName>Office 2</fullName>
                </value>
                <value>
                    <fullName>Office 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/classes/LoginControllerTest.cls
@isTest
public with sharing class LoginControllerTest {
    @isTest static void testCheckLoginData(){
        Contact testCon = new Contact();
        testCon.Admin__c = true;
        testCon.LastName = 'Test';
        testCon.Email = 'email@email.com';
        testCon.Password__c = '1111';
        testCon.Office__c = 'Office 1';
        insert testCon;
        Contact tested = LoginController.checkLoginData(testCon.Email, testCon.Password__c);
        System.assertEquals(tested.Admin__c, true);
    }
}