expense-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office 1</fullName>
                </value>
                <value>
                    <fullName>Office 2</fullName>
                </value>
                <value>
                    <fullName>Office 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/objects/Expense_Card__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CardDate__c</fullName>
        <label>Card Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Card_Keeper__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Card Keeper</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expense Cards</relationshipLabel>
        <relationshipName>ExpenseCards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Expense Card</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expense Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/objects/Monthly_Expense__c.object
<CustomObject>
    <label>Monthly Expense</label>
    <nameField>
        <displayFormat>ME-{000000}</displayFormat>
        <label>Monthly Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/src/classes/ExpensePageControllerTest.cls
@isTest
public with sharing class ExpensePageControllerTest {
    @testSetup 
    static void setup(){
        Contact c = new Contact();
        c.Admin__c = false;
        c.LastName = 'TestKeeper';
        c.Email = 'email@email.com';
        c.Password__c = '1111';
        c.Office__c = 'Office 2';
        insert c;

        Expense_Card__c testExCard1= new Expense_Card__c();
        testExCard1.Amount__c = 20;
        testExCard1.Card_Keeper__c = c.Id;
        testExCard1.CardDate__c = Date.valueOf('2020-01-01');
        testExCard1.Description__c = 'Test Description';
        insert testExCard1;
        
    }
    @isTest 
    static void testGetMonthlyExpense(){
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'TestKeeper'];
        
        
        Monthly_Expense__c getTestMonthEx = ExpensePageController.getMonthlyExpense(String.valueOf(c.Id), '1', '2020');
        System.assertNotEquals(getTestMonthEx, null);
        Monthly_Expense__c getTestMonthEx1 = ExpensePageController.getMonthlyExpense(String.valueOf(c.Id), '11', '2020');
        System.assertEquals(getTestMonthEx1, null);
          
    }
    @isTest
    static void testGetCardsDate(){
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'TestKeeper'];

        List<Date> testCardsDates = ExpensePageController.getCardsDate(c.Id, 1, '2020');
        List<Date> testCardsDates1 = ExpensePageController.getCardsDate(c.Id, 12, '2020');
        System.assert(testCardsDates.size() > 0);
        System.assert(testCardsDates1.size() == 0);  
    }
    
    @isTest
    static void testGetExCards(){
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'TestKeeper'];
        
        List<Expense_Card__c> testListExCards = ExpensePageController.getExCards(c.Id, '2020-01-01');
        System.assert(testListExCards.size() > 0);
    }
    
    @isTest 
    static void testDeleteExpenseCard(){
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'TestKeeper'];    
        Expense_Card__c ExCard = [SELECT Id, IsDeleted FROM Expense_Card__c WHERE CardDate__c = :Date.valueOf('2020-01-01')];     
        ExpensePageController.deleteExpenseCard(ExCard.Id);     
        List<Expense_Card__c> ExCards = [SELECT Id, IsDeleted FROM Expense_Card__c]; 
        System.assert(ExCards.size() == 0);
        
    }
    
    @isTest
    static void testGetYears(){
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'TestKeeper'];
        List<Integer> testListYears = ExpensePageController.getYears(c.Id);   
        System.assert(testListYears.size() > 0);
    }
    
    @isTest
    static void testTotalExCardAmount(){
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'TestKeeper'];
        Double sum = ExpensePageController.totalExCardAmount(c.Id, '2020-01-01');
        System.assertEquals(sum, 20);
        
    }
}