expense-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office 1</fullName>
                </value>
                <value>
                    <fullName>Office 2</fullName>
                </value>
                <value>
                    <fullName>Office 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/objects/Monthly_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Keeper__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Keeper</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Monthly Expenses</relationshipLabel>
        <relationshipName>MonthlyExpenses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <label>Month Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Expense</label>
    <nameField>
        <displayFormat>ME-{000000}</displayFormat>
        <label>Monthly Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/src/classes/IncomeWindowControllerTest.cls
@isTest
public with sharing class IncomeWindowControllerTest {
    @isTest
    static void testIncomeBalance(){
        Contact c = new Contact();
        c.Admin__c = true;
        c.LastName = 'Test';
        c.Email = 'email@email.com';
        c.Password__c = '1111';
        c.Office__c = 'Office 1';
        insert c;

        Monthly_Expense__c monEx = new Monthly_Expense__c();
        monEx.Balance__c = 0;
        monEx.Month_Date__c = Date.valueOf('2020-01-01');
        monEx.Keeper__c = c.Id;
        insert monEx;

        IncomeWindowController.incomeBalance(20, monEx.Id);
        Monthly_Expense__c testMonEx = [SELECT Balance__c FROM Monthly_Expense__c WHERE Id = :monEx.Id ];

        System.assertEquals(testMonEx.Balance__c, Double.valueOf(20));
    }
}