expense-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office 1</fullName>
                </value>
                <value>
                    <fullName>Office 2</fullName>
                </value>
                <value>
                    <fullName>Office 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/objects/Expense_Card__c.object
<CustomObject>
    <label>Expense Card</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expense Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/objects/Monthly_Expense__c.object
<CustomObject>
    <label>Monthly Expense</label>
    <nameField>
        <displayFormat>ME-{000000}</displayFormat>
        <label>Monthly Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

expense-app/src/classes/ExpenseCardTriggerTest.cls
@isTest
public class ExpenseCardTriggerTest {
	@isTest
    static void testTrigger(){
        Contact c = new Contact();
        c.Admin__c = true;
        c.LastName = 'TestKeeper';
        c.Email = 'email@email.com';
        c.Password__c = '1111';
        c.Office__c = 'Office 2';
        insert c;
        
        Expense_Card__c testExCard1= NewCardWizardController.createExpenseCard(c.Id, 20, 'Test1', '2020-01-01');
        Expense_Card__c testExCard2= NewCardWizardController.createExpenseCard(c.Id, 30, 'Test2', '2020-01-01');
        Expense_Card__c testExCard3= NewCardWizardController.createExpenseCard(c.Id, 30, 'Test3', '2020-12-01');
        List<Monthly_Expense__c> getTestMonCard = [SELECT Id FROM Monthly_Expense__c];
        System.assert(getTestMonCard.size() == 2);
    }
}