expense-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office 1</fullName>
                </value>
                <value>
                    <fullName>Office 2</fullName>
                </value>
                <value>
                    <fullName>Office 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/objects/Expense_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Keeper__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Card Keeper</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expense Cards</relationshipLabel>
        <relationshipName>ExpenseCards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Expense Card</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expense Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/classes/NewCardWizardControllerTest.cls
@isTest
public class NewCardWizardControllerTest {
    @isTest 
    static void testCreateExpenseCard(){
        Contact testCon = new Contact();
        testCon.Admin__c = true;
        testCon.LastName = 'Test';
        testCon.Email = 'email@email.com';
        testCon.Password__c = '1111';
        testCon.Office__c = 'Office 1';
        insert testCon;
        
        Expense_Card__c testExCard = NewCardWizardController.createExpenseCard(String.valueOf(testCon.Id), Double.valueOf(20.00), 'Test Descript', '2020-01-01');  
        System.assertEquals(testExCard.Card_Keeper__c, testCon.Id);
        
    }
}