expense-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Office 1</fullName>
                </value>
                <value>
                    <fullName>Office 2</fullName>
                </value>
                <value>
                    <fullName>Office 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/classes/LoginController.cls
public with sharing class LoginController {

    @AuraEnabled
    public static Contact checkLoginData(String email, String pass){
        try{
            Contact keeper = [SELECT Id, Name, Email, Password__c, Office__c, Admin__c FROM Contact WHERE Email = :email AND Password__c = :pass];
            System.debug(keeper);
            return keeper;
        }catch(Exception ex){
            return null;
        }
        
    }
}