expense-app/src/objects/Expense_Card__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CardDate__c</fullName>
        <label>Card Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Card_Keeper__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Card Keeper</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expense Cards</relationshipLabel>
        <relationshipName>ExpenseCards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Expense Card</label>
    <nameField>
        <displayFormat>EXP-{000000}</displayFormat>
        <label>Expense Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

expense-app/src/classes/NewCardWizardController.cls
public with sharing class NewCardWizardController {
    @AuraEnabled
    public static Expense_Card__c createExpenseCard(String keeperId, Double amount, String description, String cardDate){
        Expense_Card__c newcard = new Expense_Card__c();
        newCard.Card_Keeper__c = keeperId;
        newCard.Amount__c = amount;
        newCard.Description__c = description;
        newCard.CardDate__c = Date.valueOf(cardDate);
        
        insert newCard;
        System.debug(newCard);
        return newCard;
    }
}