exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Base_Currency__c</fullName>
        <label>Base Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GBP</fullName>
                    <default>true</default>
                    <label>GBP</label>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <inlineHelpText>Canada Dollar (C$)</inlineHelpText>
        <label>CAD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <inlineHelpText>Euro (€)</inlineHelpText>
        <label>EUR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <inlineHelpText>British Pound(£)</inlineHelpText>
        <label>GBP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <inlineHelpText>Unated State Dollar ($)</inlineHelpText>
        <label>USD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/classes/ExchangeCurrencyRateControllerTest.cls
@isTest
public class ExchangeCurrencyRateControllerTest {
	
    @isTest
    static void testGetRateByDate(){
        Date dt = Date.parse('6/19/2020');
        
        Exchange_Rate__c newTestRate = new Exchange_Rate__c();
		newTestRate.Name = 'Rate Currency 2020-06-19';
        newTestRate.Date__c = dt;
        newTestRate.Base_Currency__c = 'GBP';
        insert newTestRate;
        
        List<Exchange_Rate__c> testRate2 = ExchangeCurrencyRateController.getRateByDate('2020-6-18', '2020-6-19', '');
        
        List<Exchange_Rate__c> testRate = ExchangeCurrencyRateController.getRateByDate('2020-6-18', '2020-6-19', 'GBP');
        System.debug(testRate.size());
        System.assertEquals(1,testRate.size());
        
    }
    @isTest
    static void testEditBaseCurrency(){
        
        Exchange_Rate__c newRate = new Exchange_Rate__c();
        newRate.Name = 'TestRate';
        newRate.Base_Currency__c = 'GBP';
        newRate.CAD__c = 2.00;
        newRate.USD__c = 3.00;
        newRate.EUR__c = 0.50;
        newRate.GBP__c = 1.00;
        insert newRate;
        
        ExchangeCurrencyRateController.editBaseCurrency(newRate.Id, 'USD');
        Exchange_Rate__c rate = [SELECT Base_Currency__c FROM Exchange_Rate__c WHERE Id = :newRate.Id];
        
        System.assertEquals('USD', rate.Base_Currency__c);
    }
    
}