exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Base_Currency__c</fullName>
        <label>Base Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GBP</fullName>
                    <default>true</default>
                    <label>GBP</label>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Log</label>
        <referenceTo>Log__c</referenceTo>
        <relationshipLabel>Exchande Rates</relationshipLabel>
        <relationshipName>Exchande_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/RateResponse__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Rate_Response</label>
</CustomObject>

exchange-rate-app/src/classes/InsertSkipedRateTest.cls
@isTest
public class InsertSkipedRateTest {
	@testSetup 
    static void setup() {
        RateResponse__c rr =  new RateResponse__c();
        rr.Name__c = 'Rate';
        rr.Status__c = 'OK';
        rr.Body__c = '{"rates":{"EUR":0.8920606601},"base":"USD","date":"2020-06-19"}';
        insert rr;
        List<Log__c> logs = new List<Log__c>();
        List<Exchange_Rate__c> rates = new List<Exchange_Rate__c>();
        
        for (Integer i=0;i<10;i++) {
            Log__c log = new Log__c(Status_Code__c='ERROR');
            insert log;
        }
        
        
        for (Log__c log : [select id from Log__c]) {
            Exchange_Rate__c rate = new Exchange_Rate__c(Name='TestRate', Base_Currency__c='GBP',
                 Log__c=log.id);
            insert rate;
        }
        
    }
    static testmethod void test() {        
        Test.startTest();
        InsertSkipedRate uca = new InsertSkipedRate();
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [select count() from Exchange_Rate__c where Log__r.Status_Code__c = 'OK']);
    }
}