exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Base_Currency__c</fullName>
        <label>Base Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GBP</fullName>
                    <default>true</default>
                    <label>GBP</label>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Log</label>
        <referenceTo>Log__c</referenceTo>
        <relationshipLabel>Exchande Rates</relationshipLabel>
        <relationshipName>Exchande_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/classes/ExchangeCurrencyRateController.cls
public class ExchangeCurrencyRateController {
	@AuraEnabled
    public static List<String> getRateFromObject(){
        
        List<String> listRates= new List<String>();
        Schema.DescribeFieldResult fieldResult = Exchange_Rate__c.Base_Currency__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pickListVal : ple){
            listRates.add(pickListVal.getLabel());
        }
		System.debug(listRates);
        return listRates;
    }
    
    @AuraEnabled
    public static List<Exchange_Rate__c> getRateByDate(String d1, String d2, String selectRate){
        String rateVal;
        if(selectRate == null || selectRate == ''){
            rateVal='';
        }else{
            rateVal= ' AND Base_Currency__c = \'' + selectRate+'\'';
        }
        List<String> rateFields = getRateFromObject();
        String fields = 'Name';
        for(String field : rateFields){
            fields += ', '+field + '__c';
        }
        String[] dat1 = d1.split('-');
        String[] dat2 = d2.split('-');
 
		Date dt1 = Date.parse(dat1[1]+'/'+dat1[2]+'/'+dat1[0]);
        Date dt2 = Date.parse(dat2[1]+'/'+dat2[2]+'/'+dat2[0]);
        
        
        List<Exchange_Rate__c> rate = Database.query('SELECT Id, '+fields +', Date__c, Log__r.Status_Code__c, Base_Currency__c FROM Exchange_Rate__c WHERE Date__c >= :dt1 AND Date__c <= :dt2' + rateVal + ' ORDER BY Date__c DESC');
    	System.debug(rate);
        
        return rate;
    }
    
    @AuraEnabled
    public static void editBaseCurrency(Id rateId, String defCurrency){
        Exchange_Rate__c rate = [SELECT Base_Currency__c FROM Exchange_Rate__c WHERE Id = :rateId];
        rate.Base_Currency__c = defCurrency;
        update rate;
    }
  
    
}