exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/RateResponse__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Rate_Response</label>
</CustomObject>

exchange-rate-app/src/classes/ExchangeCurrencyRateServiceJobTest.cls
@isTest
public class ExchangeCurrencyRateServiceJobTest {
    @isTest
	public static void testJob(){
      
        RateResponse__c rr =  new RateResponse__c();
        rr.Name__c = 'Rate';
        rr.Status__c = 'OK';
        rr.Body__c = '{"rates":{"EUR":0.8920606601},"base":"USD","date":"2020-06-19"}';
        insert rr;
        
        Exchange_Rate__c er = new Exchange_Rate__c();
        er.Date__c =System.Date.Today()-1;
        insert er;
 
       
       String CRON_EXP = '0 0 0 3 9 ? 2022';
       
       String jobId = System.schedule('ExchangeCurrencyRateServiceJobTest', '0 0 0 3 9 ? 2022', new ExchangeCurrencyRateServiceJob());
      
       CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
       
       System.debug(CRON_EXP +'||'+ct.CronExpression);
       System.assertEquals(CRON_EXP, ct.CronExpression);
      
         
              
     }

}