exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Base_Currency__c</fullName>
        <label>Base Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GBP</fullName>
                    <default>true</default>
                    <label>GBP</label>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <inlineHelpText>Canada Dollar (C$)</inlineHelpText>
        <label>CAD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <inlineHelpText>Euro (€)</inlineHelpText>
        <label>EUR</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <inlineHelpText>British Pound(£)</inlineHelpText>
        <label>GBP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>USD__c</fullName>
        <inlineHelpText>Unated State Dollar ($)</inlineHelpText>
        <label>USD</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/classes/ExchangeRateTriggerTest.cls
@isTest
public class ExchangeRateTriggerTest {
	@isTest
    static void testExchangeRateTrigger(){
        Exchange_Rate__c newRate = new Exchange_Rate__c();
        newRate.Name = 'TestRate';
        newRate.Base_Currency__c = 'GBP';
        newRate.CAD__c = 2.00;
        newRate.USD__c = 3.00;
        newRate.EUR__c = 0.50;
        newRate.GBP__c = 1.00;
        insert newRate;
        System.debug(newRate);
        
        Exchange_Rate__c updateRate = [SELECT Base_Currency__c, GBP__c, EUR__c FROM Exchange_Rate__c WHERE Id =: newRate.Id];
        updateRate.Base_Currency__c = 'EUR';
        update updateRate;
        System.debug(updateRate);
        System.assertEquals(updateRate.Base_Currency__c, 'EUR');
        System.assertEquals(updateRate.EUR__c, 0.50);
        
    }
}