exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Log</label>
        <referenceTo>Log__c</referenceTo>
        <relationshipLabel>Exchande Rates</relationshipLabel>
        <relationshipName>Exchande_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/classes/InsertSkipedRate.cls
global class InsertSkipedRate implements
	Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ' + 
            String.join(new List<String>(Schema.getGlobalDescribe().get('Exchange_Rate__c').getDescribe().fields.getMap().keySet()), ',') + 
            ' FROM Exchange_Rate__c WHERE Log__r.Status_Code__c != \'ERROR\''
        );
    }
    global void execute(Database.BatchableContext bc, List<Exchange_Rate__c> rates){
        // process each batch of records
        
        for (Exchange_Rate__c rate : rates) {      
                ExchangeCurrencyRateLogic.updateRecords(rate);
                recordsProcessed = recordsProcessed + 1;      
        }
        
    }    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed.');
        
    }
}