exchange-rate-app/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Log</label>
        <referenceTo>Log__c</referenceTo>
        <relationshipLabel>Exchande Rates</relationshipLabel>
        <relationshipName>Exchande_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchande Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

exchange-rate-app/src/objects/RateResponse__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Rate_Response</label>
</CustomObject>

exchange-rate-app/src/classes/ExchangeCurrencyRateLogicTest.cls
@isTest
public class ExchangeCurrencyRateLogicTest {
	@isTest 
    static void testGetRateFromObject(){
        List<String> testList = ExchangeCurrencyRateLogic.getRateFromObject();
        System.assert(testList.size()>0);
    }
    
    @isTest
    static void testCreateNewRecod(){
        Test.setMock(HttpCalloutMock.class, new ExchangeCurrencyRateServiceMock()); 
        RateResponse__c rr =  new RateResponse__c();
        rr.Name__c = 'Rate';
        rr.Status__c = 'OK';
        rr.Body__c = '{"rates":{"EUR":0.8920606601},"base":"USD","date":"2020-06-19"}';
        insert rr;
        System.debug(rr);
        Test.startTest();
        ExchangeCurrencyRateLogic.createNewRecord();
        Test.stopTest();
        
        List<Exchange_Rate__c> rates = [SELECT Id FROM Exchange_Rate__c];
        System.debug('Rates: '+rates.size());
        System.assert(rates.size()>0);
        List<Log__c> logs = [SELECT Id FROM Log__c];
        System.debug('Logs: '+logs.size());
        System.assert(logs.size()>0);
      
    }
    @isTest
    static void testUpdateRecords(){
        Log__c log = new Log__c();
        log.Status_Code__c = null;
        log.Response_Body__c = null;
        insert log;
        
        Exchange_Rate__c newTestRate = new Exchange_Rate__c();
        newTestRate.Name = 'Test Rate';
        newTestRate.Date__c = Date.parse('6/19/2020');
        newTestRate.Log__c = log.Id;
        insert newTestRate;
        
        Test.setMock(HttpCalloutMock.class, new ExchangeCurrencyRateServiceMock()); 
        RateResponse__c rr =  new RateResponse__c();
        rr.Name__c = 'Rate';
        rr.Status__c = 'OK';
        rr.Body__c = '{"rates":{"EUR":0.8920606601},"base":"USD","date":"2020-06-19"}';
        insert rr;
        System.debug(rr);
        Test.startTest();
        ExchangeCurrencyRateLogic.updateRecords(newTestRate);
        Test.stopTest();
        
        List<Exchange_Rate__c> rates = [SELECT Id, Name FROM Exchange_Rate__c];
        System.debug('Rates: '+rates);
        System.assert(rates.size()>0);
        List<Log__c> logs = [SELECT Id FROM Log__c];
        System.debug('Logs: '+logs.size());
        System.assert(logs.size()>0);
        
        
        
        
    }
}